# Generated by Django 3.1.2 on 2021-02-16 05:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('ciudad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ciudad de origen')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='Foto de perfil')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción')),
                ('facebook', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Link cuenta de Facebook')),
                ('twitter', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Link cuenta de Twitter')),
                ('tiktok', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Link cuenta de Tiktok')),
                ('instagram', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Link cuenta de Instagram')),
                ('pinterest', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Link cuenta de Pinterest')),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('perfuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
