# Generated by Django 3.1.2 on 2021-02-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(default='inversorinteligente.png', upload_to='avatar/', verbose_name='Foto de perfil'),
        ),
    ]
