# Generated by Django 3.1.2 on 2021-02-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_auto_20210225_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='facebook',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Link de tu Facebook'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='instagram',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Link de tu Instagram'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pinterest',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Link de tu Pinterest'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tiktok',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Link de tu Tiktok'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='twitter',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Link de tu Twitter'),
        ),
    ]
