# Generated by Django 3.1.2 on 2021-02-26 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_activo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre del activo')),
                ('ticker_accion', models.CharField(blank=True, max_length=6, null=True, verbose_name='Ticker de la acción')),
                ('rendimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rendimiento')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('movimiento', models.CharField(blank=True, choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=6, null=True, verbose_name='Movimiento realizado')),
                ('fecha_movimiento', models.DateField(blank=True, null=True, verbose_name='Fecha del movimiento')),
                ('observacion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.tipo_activo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
