# Generated by Django 3.1.2 on 2021-02-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tipo_activo',
            new_name='Activo',
        ),
    ]
