# Generated by Django 3.1.2 on 2021-02-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0005_auto_20210227_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartera',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Valor'),
        ),
    ]
