# Generated by Django 3.1.2 on 2021-03-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifs',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='notifs',
            name='postw',
        ),
        migrations.AddField(
            model_name='notifs',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notifs',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Nuevo_Post'), (2, 'Nuevo_Curso')]),
        ),
    ]
