# Generated by Django 3.1.2 on 2021-02-20 04:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='contenido_curso',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
