# Generated by Django 3.1.2 on 2021-02-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_auto_20210220_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='curso/'),
        ),
        migrations.AddField(
            model_name='talleres',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='taller/'),
        ),
    ]
