# Generated by Django 3.1.2 on 2021-02-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0006_auto_20210220_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='genero',
        ),
        migrations.AddField(
            model_name='cursos',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escuela.generos'),
        ),
        migrations.RemoveField(
            model_name='talleres',
            name='genero',
        ),
        migrations.AddField(
            model_name='talleres',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escuela.generos'),
        ),
    ]
