# Generated by Django 3.1.2 on 2021-02-22 01:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0007_auto_20210220_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='contenido_curso',
        ),
        migrations.AddField(
            model_name='cursos',
            name='fecha_actualización',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escuela.generos'),
        ),
        migrations.AlterField(
            model_name='talleres',
            name='curso_relacionado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escuela.cursos'),
        ),
        migrations.AlterField(
            model_name='talleres',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escuela.generos'),
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modulo', models.CharField(blank=True, max_length=150, null=True)),
                ('contenido_modulo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='curso/')),
                ('pdf_modulo', models.FileField(blank=True, null=True, upload_to='curso/')),
                ('curso_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escuela.cursos')),
            ],
        ),
    ]
