# Generated by Django 3.1.2 on 2021-02-26 03:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0009_auto_20210223_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='resumen',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
