# Generated by Django 3.1.2 on 2021-02-20 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210216_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postweb',
            name='categoria',
            field=models.ForeignKey(blank=True, max_length=200, on_delete=django.db.models.deletion.PROTECT, to='web.category'),
        ),
    ]
