# Generated by Django 3.1.2 on 2021-02-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210219_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='postweb',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
