# Generated by Django 3.1.2 on 2021-02-17 07:09

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('resumen', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('contenido_curso', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='curso/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='curso/')),
                ('pdf_curso', models.FileField(blank=True, null=True, upload_to='curso/')),
            ],
        ),
        migrations.CreateModel(
            name='generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generos_temas', models.CharField(blank=True, max_length=150, null=True, verbose_name='Géneros de los temas')),
            ],
        ),
        migrations.CreateModel(
            name='metodos_de_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(blank=True, max_length=150, null=True, verbose_name='Método de pago')),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=150, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(blank=True, max_length=150, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='talleres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('resumen', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('herramienta', models.FileField(blank=True, null=True, upload_to='taller/')),
                ('contenido_taller', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='taller/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='taller/')),
                ('pdf_ejercicio', models.FileField(blank=True, null=True, upload_to='taller/')),
                ('pdf_correcion', models.FileField(blank=True, null=True, upload_to='taller/')),
                ('genero', models.ManyToManyField(blank=True, to='muro.generos')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='muro.metodos_de_pago')),
                ('pedido_curso', models.ManyToManyField(blank=True, to='muro.cursos')),
                ('pedido_producto', models.ManyToManyField(blank=True, to='muro.productos')),
                ('pedido_servicio', models.ManyToManyField(blank=True, to='muro.servicios')),
                ('pedido_taller', models.ManyToManyField(blank=True, to='muro.talleres')),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='genero',
            field=models.ManyToManyField(blank=True, to='muro.generos'),
        ),
    ]
