# Generated by Django 3.1.2 on 2021-02-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0002_auto_20210217_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='order',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
