# Generated by Django 3.1.2 on 2021-02-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0004_auto_20210217_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pedido_curso',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pedido_producto',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pedido_servicio',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pedido_taller',
        ),
        migrations.AddField(
            model_name='productos',
            name='pedido_curso',
            field=models.ManyToManyField(blank=True, to='muro.cursos'),
        ),
        migrations.AddField(
            model_name='productos',
            name='pedido_taller',
            field=models.ManyToManyField(blank=True, to='muro.talleres'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='pedido_curso',
            field=models.ManyToManyField(blank=True, to='muro.cursos'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='pedido_taller',
            field=models.ManyToManyField(blank=True, to='muro.talleres'),
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curs', models.ManyToManyField(blank=True, to='muro.cursos')),
                ('prod', models.ManyToManyField(blank=True, to='muro.productos')),
                ('serv', models.ManyToManyField(blank=True, to='muro.servicios')),
                ('tall', models.ManyToManyField(blank=True, to='muro.talleres')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='obj_pedido',
            field=models.ManyToManyField(blank=True, to='muro.pedido'),
        ),
    ]
