# Generated by Django 3.1.2 on 2021-02-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0006_auto_20210217_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='obj_pedido',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='pedido_curso',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='pedido_taller',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='pedido_curso',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='pedido_taller',
        ),
        migrations.AddField(
            model_name='order',
            name='prod_pedido',
            field=models.ManyToManyField(blank=True, to='muro.productos'),
        ),
        migrations.AddField(
            model_name='order',
            name='serv_pedido',
            field=models.ManyToManyField(blank=True, to='muro.servicios'),
        ),
        migrations.DeleteModel(
            name='pedido',
        ),
    ]
