# Generated by Django 3.1.2 on 2021-02-18 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0007_auto_20210217_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prod_pedido',
        ),
        migrations.AddField(
            model_name='order',
            name='prod_pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='muro.productos'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='serv_pedido',
        ),
        migrations.AddField(
            model_name='order',
            name='serv_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='muro.servicios'),
        ),
    ]
