# Generated by Django 3.1.6 on 2021-02-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0008_auto_20210217_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
