# Generated by Django 3.1.6 on 2021-02-18 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0009_auto_20210218_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='muro.metodos_de_pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prod_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='muro.productos'),
        ),
    ]
