# Generated by Django 3.1.2 on 2021-02-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0010_auto_20210218_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talleres',
            name='genero',
        ),
        migrations.DeleteModel(
            name='cursos',
        ),
        migrations.DeleteModel(
            name='generos',
        ),
        migrations.DeleteModel(
            name='talleres',
        ),
    ]
