# Generated by Django 3.1.2 on 2021-02-22 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0011_auto_20210219_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Cantidad de productos pedidos'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización del servicio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del servicio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prod_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='muro.productos'),
        ),
        migrations.AlterField(
            model_name='order',
            name='serv_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='muro.servicios'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='servicio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del servicio'),
        ),
    ]
