# Generated by Django 3.1.2 on 2021-02-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='comentador',
        ),
    ]
