# Generated by Django 3.1.2 on 2021-02-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20210215_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellidos'),
        ),
    ]
