# Generated by Django 3.1.2 on 2021-02-16 23:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20210216_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Número telefónico'),
        ),
    ]
